# Generated by Django 5.2.4 on 2025-11-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonial'),
        ('products', '0012_remove_product_gender_alter_size_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='curated_edits/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='curated_edits', to='products.product')),
            ],
            options={
                'verbose_name': 'Curated Edit',
                'verbose_name_plural': 'Curated Edits',
            },
        ),
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='featured_collections', to='products.product')),
            ],
            options={
                'verbose_name': 'Featured Collection',
                'verbose_name_plural': 'Featured Collections',
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_url', models.CharField(default='/products/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
            },
        ),
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='journal/')),
                ('category', models.CharField(choices=[('style_guide', 'Style Guide'), ('sustainability', 'Sustainability'), ('trends', 'Trends'), ('accessories', 'Accessories'), ('history', 'History'), ('seasonal', 'Seasonal')], max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journal Post',
                'verbose_name_plural': 'Journal Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
            },
        ),
        migrations.DeleteModel(
            name='FeaturedItem',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
