# Generated by Django 5.2.4 on 2025-11-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_curatededit_featuredcollection_herobanner_and_more'),
        ('products', '0012_remove_product_gender_alter_size_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curatededit',
            options={'ordering': ['display_order', '-is_featured', '-created_at'], 'verbose_name': 'Curated Edit', 'verbose_name_plural': 'Curated Edits'},
        ),
        migrations.AddField(
            model_name='curatededit',
            name='button_text',
            field=models.CharField(default='Shop Now', help_text='Text for the call-to-action button', max_length=50),
        ),
        migrations.AddField(
            model_name='curatededit',
            name='button_url',
            field=models.CharField(blank=True, help_text='URL for the call-to-action button (leave blank to auto-generate)', max_length=200),
        ),
        migrations.AddField(
            model_name='curatededit',
            name='category',
            field=models.CharField(choices=[('bestsellers', 'Best Sellers'), ('new_arrivals', 'New Arrivals'), ('seasonal', 'Seasonal'), ('trending', 'Trending Now'), ('editor_pick', "Editor's Pick"), ('limited_edition', 'Limited Edition')], default='editor_pick', help_text='Category/type of the curated edit', max_length=50),
        ),
        migrations.AddField(
            model_name='curatededit',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which edits appear (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='curatededit',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured edit'),
        ),
        migrations.AddField(
            model_name='curatededit',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Optional secondary image', null=True, upload_to='curated_edits/'),
        ),
        migrations.AddField(
            model_name='curatededit',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle', max_length=300),
        ),
        migrations.AddField(
            model_name='curatededit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='curatededit',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the edit'),
        ),
        migrations.AlterField(
            model_name='curatededit',
            name='image',
            field=models.ImageField(help_text='Main display image', upload_to='curated_edits/'),
        ),
        migrations.AlterField(
            model_name='curatededit',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this edit on the website'),
        ),
        migrations.AlterField(
            model_name='curatededit',
            name='products',
            field=models.ManyToManyField(help_text='Products featured in this edit', related_name='curated_edits', to='products.product'),
        ),
        migrations.AlterField(
            model_name='curatededit',
            name='title',
            field=models.CharField(help_text='Display title for the curated edit', max_length=200),
        ),
    ]
