# Generated by Django 5.2.4 on 2025-11-10 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_curatededit_options_curatededit_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Menu name (e.g., 'Shop', 'Collections')", max_length=100)),
                ('slug', models.SlugField(help_text='URL slug for the menu', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this menu in navigation')),
            ],
            options={
                'verbose_name': 'Mega Menu',
                'verbose_name_plural': 'Mega Menus',
            },
        ),
        migrations.CreateModel(
            name='MegaMenuColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Column title (e.g., 'Clothing', 'New Arrivals')", max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of columns in the menu')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.megamenu')),
            ],
            options={
                'verbose_name': 'Mega Menu Column',
                'verbose_name_plural': 'Mega Menu Columns',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MegaMenuFeatured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Featured section title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Featured section subtitle', max_length=300)),
                ('image', models.ImageField(help_text='Featured image', upload_to='mega_menu_featured/')),
                ('button_text', models.CharField(default='Shop Now', help_text='Button text', max_length=50)),
                ('button_url', models.CharField(default='/products/', help_text='Button URL', max_length=200)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='core.megamenu')),
            ],
            options={
                'verbose_name': 'Mega Menu Featured',
                'verbose_name_plural': 'Mega Menu Featured Sections',
            },
        ),
        migrations.CreateModel(
            name='MegaMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Link text', max_length=100)),
                ('url', models.CharField(help_text='Link URL', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of links in the column')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this link')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.megamenucolumn')),
            ],
            options={
                'verbose_name': 'Mega Menu Link',
                'verbose_name_plural': 'Mega Menu Links',
                'ordering': ['display_order'],
            },
        ),
    ]
