# Generated by Django 5.2.4 on 2025-11-10 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_megamenu_megamenucolumn_megamenufeatured_and_more'),
        ('products', '0012_remove_product_gender_alter_size_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megamenucolumn',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='megamenufeatured',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='megamenulink',
            name='column',
        ),
        migrations.CreateModel(
            name='HomePageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(blank=True, help_text='Custom title for home page (optional)', max_length=200)),
                ('display_description', models.TextField(blank=True, help_text='Custom description for home page (optional)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance on home page')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured product')),
                ('is_active', models.BooleanField(default=True, help_text='Show on home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_feature', to='products.product')),
            ],
            options={
                'verbose_name': 'Home Page Product',
                'verbose_name_plural': 'Home Page Products',
                'ordering': ['display_order', '-is_featured', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MegaMenu',
        ),
        migrations.DeleteModel(
            name='MegaMenuFeatured',
        ),
        migrations.DeleteModel(
            name='MegaMenuColumn',
        ),
        migrations.DeleteModel(
            name='MegaMenuLink',
        ),
    ]
