# Generated by Django 5.2.4 on 2025-11-12 07:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_megamenucolumn_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatededit',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Main display image', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='curatededit',
            name='secondary_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional secondary image', max_length=255, null=True, verbose_name='secondary_image'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='background_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
