# Generated by Django 5.2.4 on 2025-11-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_curatededit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatededit',
            name='image',
            field=models.ImageField(help_text='Main display image', upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='curatededit',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Optional secondary image', null=True, upload_to='', verbose_name='secondary_image'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='background_image',
            field=models.ImageField(upload_to='', verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
