# Generated by Django 5.2.4 on 2025-11-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20251105_1817'),
    ]

    operations = [
    ]
